// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rwfM4IdlCfW50MuMagzwRS34peAdZPM',
    appId: '1:322678416517:android:eaef7a0eccfb948c1535ec',
    messagingSenderId: '322678416517',
    projectId: 'mentor-mentee-connecting',
    storageBucket: 'mentor-mentee-connecting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-5p6QV47-qU02J6xVdNKEucnX6ImuNA',
    appId: '1:322678416517:ios:006ac0f3f49e7bac1535ec',
    messagingSenderId: '322678416517',
    projectId: 'mentor-mentee-connecting',
    storageBucket: 'mentor-mentee-connecting.appspot.com',
    androidClientId: '322678416517-i2j835ua60bbf0cn8n9e18hlotpum8t2.apps.googleusercontent.com',
    iosClientId: '322678416517-e5ff9ek7khrmlc57s97dtom4k4ovn7ee.apps.googleusercontent.com',
    iosBundleId: 'com.endy.MentorMenteeConnecting',
  );
}
